version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    container_name: portfolio-frontend
    restart: unless-stopped

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    container_name: portfolio-backend
    restart: unless-stopped
    environment:
      - NODE_ENV=production